# CACHE_BUSTER=v11 - This comment forces a rebuild
ARG CACHE_BUSTER=v12

# --- Dockerfile for ERPNext on Railway ---
ARG ERPNEXT_VERSION=v15
FROM frappe/erpnext:v15

# Switch to root
USER root

# This new RUN command will force the cache to break
RUN echo "--- Forcing a rebuild v11 ---"

# Copy our NEW entrypoint script
COPY entrypoint.v2.sh /entrypoint.v2.sh

# Make the script executable
RUN chmod +x /entrypoint.v2.sh

EXPOSE 8000

# We stay as root
USER root
