# CACHE_BUSTER=v6 - This comment forces a rebuild

# --- Dockerfile for ERPNext on Railway ---
ARG CACHE_BUSTER=v8

ARG ERPNEXT_VERSION=v15
FROM frappe/erpnext:${ERPNEXT_VERSION}

# Switch to root to copy files and set permissions
USER root

# Copy our entrypoint script into the container
COPY entrypoint.sh /entrypoint.sh

# Make the script executable
RUN chmod +x /entrypoint.sh

EXPOSE 8000

# We stay as root
USER root
